version: '3.8'

networks:
  airbus_network:
        driver: bridge
        name: airbus_network

services:
  marklogic:
    image: store/marklogicdb/marklogic-server:${mlVersion}-dev-centos
    extra_hosts:
      host.docker.internal: host-gateway
    ports:
        - "${mlSystemPortMapping}"
        - "${mlApplicationPortMapping}"
    hostname: "${mlHost}"
    container_name: "${mlHost}"
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=${mlAdmin}
      - MARKLOGIC_ADMIN_PASSWORD=${mlPassword}
      - TZ=Europe/Amsterdam
    volumes:
      - ./volumes/${mlHost}/:/var/opt/MarkLogic/:delegated
      - ${baseVolume}/data:/data
    networks:
      - airbus_network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12G
